require: rubocop-rails
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'Gemfile'
    - 'spec/**/*'
    - 'Rakefile'
    - 'vendor/bundle/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
 
Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
